### PR TITLE
fix Wii compilation

### PR DESCRIPTION
**Pull request by metallic77**

### CODE REVIEW

**Comment by inactive123** [comment]
Hi there, the build is now broken for Vita -

http://paste.libretro.com/205457

Can you fix this please?

**Comment by inactive123** [comment]
Hmm, more RetroArch builds for various platforms are now failing - PSP and 3DS too.

I'm afraid I will have to revert this because we cannot afford several platforms to no longer work in their entirety. If you can come up with a commit that still does what you want it to do without breaking these platforms, please send a PR.

**Comment by metallic77** [comment]
Probably because i removed compiling sam.cpp from Wii (it's an assembly monitor), on makefile.common with an ifndef directive, could be that the other platforms need to compile it and cannot find it where they look for it. I can't see any other reason, the other changes are Wii specific

**Comment by metallic77** [comment]
I guess the error is 

ifneq ($(platform), wii)
SOURCES_CXX := \
		$(EMU)/SAM.cpp

Should be SOURCES_CXX += \

I'll send another PR later

**Pull request merged**
